[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mcp-python"
version = "0.1.5.dev"
description = "Model Context Protocol implementation for Python"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anyio",
    "httpx",
    "httpx-sse",
    "pydantic>=2.0.0",
    "starlette",
    "sse-starlette",
]

[tool.hatch.build.targets.wheel]
packages = ["mcp_python"]

[tool.pyright]
include = ["mcp_python", "tests"]
venvPath = "."
venv = ".venv"

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []

[tool.ruff]
line-length = 88
target-version = "py38"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.uv]
dev-dependencies = [
    "trio>=0.26.2",
]
